export default class DisplayFormats {
	static DISPLAY_FORMAT_FILL = 'DISPLAY_FORMAT_FILL';
	static DISPLAY_FORMAT_WIDE_2_39_1 = 'DISPLAY_FORMAT_WIDE_2_39_1';
	static DISPLAY_FORMAT_WIDE_2_1 = 'DISPLAY_FORMAT_WIDE_2_1';
	static DISPLAY_FORMAT_WIDE_4_3 = 'DISPLAY_FORMAT_WIDE_4_3';
	static DISPLAY_FORMAT_SQUARE = 'DISPLAY_FORMAT_SQUARE';
}
